### ISSUE TITLE
SAXNotSupportedException FEATURE_SECURE_PROCESSING with external xsd ran by Eclipse Maven Builder

### ISSUE THREAD

**Issue by arenagabriel** [highsource/maven-jaxb2-plugin#104]
I use the plugin with external schema (over http) and errors are shown in eclipse problems tab (when maven builder has been executed) :

![error](https://cloud.githubusercontent.com/assets/17003776/20803190/a04026ba-b7ee-11e6-9c24-6154393adffd.png)

Execution v010 of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING : impossible de définir la fonctionnalité sur False en présence du gestionnaire de sécurité. (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate:v010:generate-sources)

org.apache.maven.plugin.PluginExecutionException: Execution v010 of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING : impossible de définir la fonctionnalité sur False en présence du gestionnaire de sécurité.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.IllegalStateException: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING : impossible de définir la fonctionnalité sur False en présence du gestionnaire de sécurité.
	at com.sun.xml.bind.v2.util.XmlFactory.createSchemaFactory(XmlFactory.java:109)
	at com.sun.tools.xjc.reader.xmlschema.parser.SchemaConstraintChecker.check(SchemaConstraintChecker.java:86)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:360)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 31 more
Caused by: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING : impossible de définir la fonctionnalité sur False en présence du gestionnaire de sécurité.
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.setFeature(XMLSchemaFactory.java:365)
	at com.sun.xml.bind.v2.util.XmlFactory.createSchemaFactory(XmlFactory.java:102)
	... 41 more
	pom.xml	/schemabook-tools	line 42	Maven Build Problem

This is the plugin configuration : 

`
<plugins>
	<plugin>
		<groupId>org.jvnet.jaxb2.maven2</groupId>
		<artifactId>maven-jaxb2-plugin</artifactId>
		<version>0.13.1</version>
		<executions>
			<execution>
				<id>v010</id>
				<goals>
					<goal>generate</goal>
				</goals>
				<configuration>
					<encoding>UTF-8</encoding>
					<schemas><schema> <url>http://schemas.url/schemabook/app/app_v010.xsd</url></schema></schemas>		
					<generateDirectory>src/main/gen</generateDirectory>	
					<generatePackage>app_v010</generatePackage>
				</configuration>
			</execution>
		</executions>
	</plugin>
</plugins>
`

XSD url file is OK in intranet..

When I launch mvn package on project, the error is not thrown.

So the problem is just visible when plugin is executed in m2e plugin. It could be a problem on a security java file which would be different in m2e context / classpath ?
Someone has an idea ?

Thanks for your help.

Gabriel

**Comment by highsource** [comment]
The plugin sets a couple of system properties to be able to access external schemas (`accessExternalSchema` option).

Apparently when executing in Eclipse/m2eclipse, these properties are either not set or ignored. There is nothing I can do. You should set `javax.xml.accessExternalSchema` and/or `javax.xml.accessExternalDTD` to `all`. See [this](https://github.com/highsource/maven-jaxb2-plugin/blob/1de6b67de2a5b7d08eb1b2757dec759c74157e3f/plugin-2.0/src/main/java/org/jvnet/mjiip/v_2_0/OptionsFactory.java#L57-L64).

Anyway I stronly advise against compiling online resources. Make local copies and use catalog files to rewrite URLs.

**Comment by arenagabriel** [comment]
Thanks for your response Alexey.

I think it's really too bad to change the configuration to use local schemas, because m2e plugin throw an error ... I would like to find a workaround for eclipse, despites I have not really the time ...

So I've tried to put options "accessExternalSchema" and "accessExternalDTD" in configuration tag of the plugin, and it doesn't work.

I've tried to use org.codehaus.mojo:properties-maven-plugin:1.0.0 plugin in order to set system properties javax.xml.accessExternalSchema=all and javax.xml.accessExternalDTD=all, but it doesn't work.

The problem seems to be thrown after the configuration in jaxb2-plugin. When SAXParser is executed, the code use System.getSecurityManager() and retrieve a policy file set when executing the m2e plugin.

I'm not really fluent with java security ... and in maven stack, it's difficult to see / log this behaviour.

**Comment by highsource** [comment]
You should not change config to local files because of m2eclispe, you should change it because it is the right way. Builds should not depend on online resources.

Setting `accessExternalSchema` and `accessExternalDTD` in the configuration won't help because they are already set to `all` by default. I also don't thing setting these properties from other Maven plugins will help either. If it would work with other plugins, it would have worked with `maven-jaxb2-plugin` either. 

Try setting these system properties globally for Eclipse.

**Comment by arenagabriel** [comment]
I've tried to put them into eclipse.ini (vmargs section), it doesn't work.
Tried also, to put into jaxp.properties, and place the file in resources classpath of the project ;
Next, place the file, in classpath of eclipse ;
Next, place the file in lib folder of jre home (used by eclipse with vm arg in eclipse.ini) ;
These 3 tests don't work.
I must find how the classpath used by m2e pluggin is built...

**Comment by matejsp** [comment]
I have the same problem ... but I am compiling one simple .xsd inside /src/main/resources/

<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sample.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
    
    <element name="test2">
		<complexType>
			<sequence>
				<element name="bla" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
    </element>
</schema>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.13.2</version>
				<executions>
					<execution>
						<id>translations-jaxb</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
				<configuration>
					<schemaDirectory>src/main/resources/xsd</schemaDirectory>
				</configuration>
			</plugin>
		</plugins>
	</build>


Execution translations-jaxb of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate failed: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING: Cannot set the feature to false when security manager is present. (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate:translations-jaxb:generate-sources)

org.apache.maven.plugin.PluginExecutionException: Execution translations-jaxb of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate failed: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING: Cannot set the feature to false when security manager is present.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.IllegalStateException: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING: Cannot set the feature to false when security manager is present.
	at com.sun.xml.bind.v2.util.XmlFactory.createSchemaFactory(XmlFactory.java:109)
	at com.sun.tools.xjc.reader.xmlschema.parser.SchemaConstraintChecker.check(SchemaConstraintChecker.java:86)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:360)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:471)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:314)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 31 more
Caused by: org.xml.sax.SAXNotSupportedException: FEATURE_SECURE_PROCESSING: Cannot set the feature to false when security manager is present.
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.setFeature(Unknown Source)
	at com.sun.xml.bind.v2.util.XmlFactory.createSchemaFactory(XmlFactory.java:102)
	... 41 more

**Comment by matejsp** [comment]
I think I have found out the problematic extension.
In my case the problematic plugin was takari-lifecycle integration.
http://takari.io/book/40-lifecycle.html#installing-eclipse-m2e-integration
I got rid of it and maven-jaxb2-plugin works again.

**Comment by victornoel** [comment]
@matejsp good find, I had the same problem and this extension was creating the problem…

**Comment by highsource** [comment]
I guess the problem is solved by now.
