### ISSUE TITLE
The "jaxb:globalBindings" customization is not associated with any schema element

### ISSUE THREAD

**Issue by nixgadget** [highsource/maven-jaxb2-plugin#112]
Despite of having,

```
<jaxb:bindings xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
               xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb http://java.sun.com/xml/ns/jaxb/bindingschema_2_0.xsd"
               version="2.1">
    <jaxb:globalBindings typesafeEnumMaxMembers="270">
        <xjc:simple/>
    </jaxb:globalBindings>
</jaxb:bindings>
```

I seem to be getting,

```
[INFO] --- maven-jaxb2-plugin:0.13.0:generate (jaxb2-user) @ onboarding ---
[INFO] Up-to-date check for source resources [[file:/Volumes/STORAGE/Projects/Test/onboarding/src/main/resources/wsdl/3_2_6/user/Contract.wsdl, file:/Volumes/STORAGE/Projects/Test/onboarding/src/main/resources/wsdl/3_2_6/user/UserDataService.wsdl, file:/Volumes/STORAGE/Projects/Test/onboarding/src/main/resources/bindings/binding.xjb, file:/Volumes/STORAGE/Projects/Test/onboarding/pom.xml]] and target resources [[]].
[INFO] Sources are not up-to-date, XJC will be executed.
[ERROR] Error while parsing schema(s).Location [ file:/Volumes/STORAGE/Projects/Test/onboarding/src/main/resources/bindings/binding.xjb{41,55}].
com.sun.istack.SAXParseException2; systemId: file:/Volumes/STORAGE/Projects/Test/onboarding/src/main/resources/bindings/binding.xjb; lineNumber: 41; columnNumber: 55; The "jaxb:globalBindings" customization is not associated with any schema element.
	at com.sun.tools.xjc.reader.internalizer.Internalizer.reportError(Internalizer.java:624)
	at com.sun.tools.xjc.reader.internalizer.Internalizer.reportError(Internalizer.java:618)
	at com.sun.tools.xjc.reader.internalizer.Internalizer.move(Internalizer.java:427)
	at com.sun.tools.xjc.reader.internalizer.Internalizer.transform(Internalizer.java:153)
	at com.sun.tools.xjc.reader.internalizer.Internalizer.transform(Internalizer.java:107)
	at com.sun.tools.xjc.reader.internalizer.DOMForest.transform(DOMForest.java:439)
	at com.sun.tools.xjc.ModelLoader.buildDOMForest(ModelLoader.java:345)
	at com.sun.tools.xjc.ModelLoader.loadWSDL(ModelLoader.java:391)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:170)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Any ideas what could be causing this ?

**Comment by to4kin** [comment]
Have you fixed this issue?

**Comment by MeteorBoom** [comment]
Same here. How to solve this?

**Comment by MeteorBoom** [comment]
Maybe it will help someone. I have some two wsdl files for external system. One of them includes the other and it (that have include statement) don't have any schema elements. While binding process plugin gets first file, don't find any schema elements and throws error. I get rid of first file and after that plugin has successfully generated all needed classes.
