### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by johnpoth** [highsource/maven-jaxb2-plugin#114]
When using Java 9 build 156 and v0.13.1 of the plugin on Apache [Camel](https://github.com/apache/camel/tree/master/components/camel-jmx) I get:
```
[WARNING] Error injecting: org.jvnet.mjiip.v_2.XJC2Mojo
java.lang.IllegalAccessError: superclass access check failed: class org.jvnet.jaxb2.maven2.resolver.tools.MavenCatalogResolver (in unnamed module @0x1b5a1d85) cannot access class com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver (in module java.xml) because module java.xml does not export com.sun.org.apache.xml.internal.resolver.tools to unnamed module @0x1b5a1d85
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:977)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:172)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:543)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:451)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:445)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:444)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3053)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2315)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:658)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:881)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:804)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1005)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1037)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1000)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1091)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1011)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:543)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Work around is to set
```
export MAVEN_OPTS="--add-exports=java.xml/com.sun.org.apache.xml.internal.resolver.tools=ALL-UNNAMED --add-exports=java.xml/com.sun.org.apache.xml.internal.resolver=ALL-UNNAMED --add-modules java.activation"
```

which works. The plugin doesn't seem to support forking so I don't see another workaround.

Thanks!

**Comment by nicolaiparlog** [comment]
To make the setting project specific I used [`${maven.projectBasedir}/.mvn/jvm.config`](https://maven.apache.org/docs/3.3.1/release-notes.html#JVM_and_Command_Line_Options). I needed an additional module, so it looks as follows:

```
--add-modules java.activation,java.xml.bind
--add-exports java.xml/com.sun.org.apache.xml.internal.resolver=ALL-UNNAMED
--add-exports java.xml/com.sun.org.apache.xml.internal.resolver.tools=ALL-UNNAMED
```

This is really just a workaround - I think the plugin should allow to be run in its own process so that JVM arguments can be passed to it.

**Comment by selckin** [comment]
Any way to work around the following ?

 [ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:testXjc (resume-xjc) on project hrxml-schema: Execution resume-xjc of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:testXjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:testXjc: com/sun/codemodel/CodeWriter

**Comment by ptahchiev** [comment]
Yep, same exception here. Any plans when we will see this resolved?

**Comment by highsource** [comment]
@selckin 

> [ERROR] Failed to execute goal org.codehaus.mojo:**jaxb2-maven-plugin**:2.3.1:testXjc (resume-xjc) on project hrxml-schema: Execution resume-xjc of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:testXjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:testXjc: com/sun/codemodel/CodeWriter

You're in the wrong project. This is `maven-jaxb2-plugin` here. `jaxb2-maven-plugin` is a completely different plugin/project.

**Comment by highsource** [comment]
@johnpoth @nicolaiparlog @ptahchiev 

Sorry guy, I have no knowledge of Java 9 module system and no idea what's happening here and how to fix it.
No idea, no plans, sorry.

**Comment by selckin** [comment]
@highsource  Sorry about that :(

(i've deleted my comment to not be in google and redirect people here with the same problem, I suggest you do the same.)

**Comment by ptahchiev** [comment]
I believe what's happening is you depend on:
```
                <jaxb22.version>2.2.11</jaxb22.version>
```

but there's already a 2.3.0 version of JAXB which ships a jaxb-jxc-jdk9 module:

http://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-jxc-jdk9/

I believe what you should do is create a new branch of the maven plugin which declares the jdk9 dependencies and release a new version that supports jdk9.

**Comment by hendriks73** [comment]
Anything to get this resolved soon, would be much appreciated. People are trying to migrate to Java9 and actually Java10 now.

**Comment by patexoid** [comment]
I moved to org.apache.cxf:cxf-xjc-plugin, some headache with configuration and it works fine for me

**Comment by highsource** [comment]
I hear you, but, as said above have zero Java 9 exp so far.

**Comment by dzmitryh** [comment]
as far as I understand(correct me if I'm wrong) the fix for it is already in java-9 branch according to discussion there -> https://github.com/highsource/maven-jaxb2-plugin/issues/120 so question is what blocks us to relase it ?

**Comment by highsource** [comment]
#120 is open. Some work was done but there was a number of problems reported.

**Comment by highsource** [comment]
@nicolaiparlog @dzmitryh @hendriks73 @ptahchiev 

Hi everyone,

I've just added the `maven-jaxb23-plugin` on the `java-9` branch. With this plugin, the `tests/java-9` by @nicolaiparlog more or less works. You still have to turn off episode generation, but schema bindings are considered.

Could you please give it a try on your projects. Thank you.

Best wishes,
Alexey

**Comment by nicolaiparlog** [comment]
Does that mean the additional `--add-exports` and `--add-modules` are no longer necessary? I went looking for the `jvm.config` file I created, but couldn't find it. I assume that means it's not needed anymore. That would be great! :)

(Will give the new version a try this or next week.)

**Comment by highsource** [comment]
@nicolaiparlog To be honest, I have no idea. The `java-9` test worked on my machine under Java 9 as it is. If don't know if this is due to my setup or it generally works. This is why I'm asking you to please give it a try.

Please also check if `maven-jaxb23-plugin` works under Java 8 for you. I would like to know if there are compatibility issues, would there be a need for Java <= 8 version of `maven-jaxb23-plugin` and Java >=9 version `maven-jaxb23-plugin` or would one variant suffice.

**Comment by nicolaiparlog** [comment]
I summarized my observations and answers to some of your questions in [this comment](https://github.com/highsource/maven-jaxb2-plugin/issues/120#issuecomment-387068435) on #120.

As I see it, this issue can be closed.

**Comment by highsource** [comment]
@SamSuffit See #120 let's continue the discussion there.

**Comment by aznan2** [comment]
Great! Now get to fixing jaxb2-basics :)

**Comment by adlmez** [comment]
+1

**Comment by adlmez** [comment]
Thanks a lot !

**Comment by highsource** [comment]
@nicolaiparlog @ptahchiev @dzmitryh @hendriks73 et al.

I've just released `maven-jaxb2-plugin` version 0.14.0 to the Central Maven Repo. Will appear there in an hour or so.

Please test it. `maven-jaxb2-plugin` or `maven-jaxb23-plugin` should work under Java 9 as well as 1.7 and 1.8.

`maven-jaxb20-plugin`, `maven-jaxb22-plugin`, `maven-jaxb22-plugin` should work under 1.7 and 1.8.

Java 1.6 is no longer supported.

**Comment by highsource** [comment]
@aznan2 See https://github.com/highsource/jaxb2-basics/releases/tag/0.12.0

**Comment by SamSuffit** [comment]
Thanks a lot !
