### ISSUE TITLE
org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate failed: Prefix '' is already bound to ''

### ISSUE THREAD

**Issue by rkrajukhunt** [highsource/maven-jaxb2-plugin#181]
xecution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate failed: Prefix '' is already bound to 
 '' (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate:default:generate-sources) org.apache.maven.plugin.PluginExecutionException: 
 Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.2:generate failed: Prefix '' is already bound to '' at 
 org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$7(MavenImpl.java:1342) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1341) at 
 org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:173) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:116) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:106) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:201) at 
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) 
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263) at 
 org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45) 
 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371) at 
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154) at 
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) Caused 
 by: java.lang.IllegalArgumentException: Prefix '' is already bound to '' at com.sun.xml.txw2.StartTag.addNamespaceDecl(StartTag.java:191) at 
 com.sun.xml.txw2.ContainerElement._namespace(ContainerElement.java:333) at java.base/
 jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/
 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/
 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/
 java.lang.reflect.Method.invoke(Method.java:566) at com.sun.xml.txw2.ContainerElement.invoke(ContainerElement.java:134) at com.sun.proxy.
 $Proxy73._namespace(Unknown Source) at com.sun.tools.xjc.addon.episode.PluginImpl.run(PluginImpl.java:174) at 
 com.sun.tools.xjc.model.Model.generateCode(Model.java:292) at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66) at 
 org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41) at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28) at 
 org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:471) at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:
 314) at org.apache

**Comment by laurentschoelens** [comment]
Hi @rkrajukhunt 
Thank you for using this plugin
Could you provide more details about your problem ? Here, we only have a stacktrace with no idea of the configuration, files you're using...
Feel free to come back with more details. Without, I'm afraid we won't be able to help much...
