### ISSUE TITLE
Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed

### ISSUE THREAD

**Issue by JakesIV** [highsource/maven-jaxb2-plugin#183]
my POM config
`<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.14.0</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<schemaLanguage>WSDL</schemaLanguage>
					<generatePackage>com.dectechsolutions.Instinct</generatePackage>
					<schemas>
						<schema>
							<url>https://hostname/service?wsdl</url>
						</schema>
					</schemas>
				</configuration>
			</plugin>`
produces error

Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed. (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate:default:generate-sources)

org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:333)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$7(MavenImpl.java:1380)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:173)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:116)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:106)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:201)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at com.sun.tools.xjc.ModelLoader.loadWSDL(ModelLoader.java:390)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:158)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:117)
	at org.jvnet.mjiip.v_2_3.XJC23Mojo.loadModel(XJC23Mojo.java:50)
	at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute(XJC23Mojo.java:40)
	at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute(XJC23Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:478)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:320)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 30 more

**Comment by airtonferreira** [comment]
Are you resolved this problem?

**Comment by highsource** [comment]
Please post the complete `mvn clean install` log for starters.

**Comment by FernandoReynosoMartinez** [comment]
i have this same problem! help me

**Comment by nrnazifi** [comment]
I fix it by putting my <plugins> inside of a <pluginManagement> tag. Somehow this makes it different for maven and it actually picks up the correct information.

**Comment by bpedroso** [comment]
When I had this problem it was the WSDL url that was wrong.  I solved the problem by pointing to the WSDL file I put in resources.
Andchange <schemas> by

<schemaFiles>META-INF/service.wsdl</schemaFiles>

**Comment by laurentschoelens** [comment]
@FernandoReynosoMartinez if you still have the problem, please generate new issue with full logs details attached and sample

**Comment by laurentschoelens** [comment]
> my POM config
> `<plugin>
> 				<groupId>org.jvnet.jaxb2.maven2</groupId>
> 				<artifactId>maven-jaxb2-plugin</artifactId>
> 				<version>0.14.0</version>
> 				<executions>
> 					<execution>
> 						<goals>
> 							<goal>generate</goal>
> 						</goals>
> 					</execution>
> 				</executions>
> 				<configuration>
> 					<schemaLanguage>WSDL</schemaLanguage>
> 					<generatePackage>com.dectechsolutions.Instinct</generatePackage>
> 					<schemas>
> 						<schema>
> 							<url>https://hostname/service?wsdl</url>
> 						</schema>
> 					</schemas>
> 				</configuration>
> 			</plugin>`
> produces error
> 
> Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed. (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate:default:generate-sources)
> 
> org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed.
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:333)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$7(MavenImpl.java:1380)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379)
> 	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:173)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:116)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:106)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:201)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.lang.NullPointerException
> 	at com.sun.tools.xjc.ModelLoader.loadWSDL(ModelLoader.java:390)
> 	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:158)
> 	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:117)
> 	at org.jvnet.mjiip.v_2_3.XJC23Mojo.loadModel(XJC23Mojo.java:50)
> 	at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute(XJC23Mojo.java:40)
> 	at org.jvnet.mjiip.v_2_3.XJC23Mojo.doExecute(XJC23Mojo.java:28)
> 	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:478)
> 	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:320)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
> 	... 30 more
> 

@JakesIV do you managed to get this fixed ?
If so, what was the problem ?
