### ISSUE TITLE
Error when upgrading from 0.9.1 to 0.12.3

### ISSUE THREAD

**Issue by gbonk** [highsource/maven-jaxb2-plugin#54]
I am trying to upgrade my plugin version and now with the latest version I now get this error.

````
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (default) on project item-ws: Error parsing catalog [maven:com.anfcorp.service.canonical:canonical:jar::!/canonical-catalog.xml]. unknown protocol: maven -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (default) on project item-ws: Error parsing catalog [maven:com.anfcorp.service.canonical:canonical:jar::!/canonical-catalog.xml].
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error parsing catalog [maven:com.anfcorp.service.canonical:canonical:jar::!/canonical-catalog.xml].
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.parseResolvedCatalogURIs(RawXJC2Mojo.java:1061)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.setupCatalogResolver(RawXJC2Mojo.java:823)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:437)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:311)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.net.MalformedURLException: unknown protocol: maven
	at java.net.URL.<init>(URL.java:574)
	at java.net.URL.<init>(URL.java:464)
	at java.net.URL.<init>(URL.java:413)
	at java.net.URI.toURL(URI.java:1080)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.parseResolvedCatalogURIs(RawXJC2Mojo.java:1058)
	... 24 more
`
````

Some of the Key environment settings are as follows....

Maven home: C:\apache-maven-3.1.1\bin\..
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: c:\Program Files\Java\jdk1.6.0_45\jre

And my plugin config, which didn't change other than the version.  

````
			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.12.3</version>
				<configuration>
					<strict>false</strict>
					<catalogs>
						<catalog>
							<dependencyResource>
								<groupId>com.anfcorp.service.canonical</groupId>
								<artifactId>canonical</artifactId>
								<resource>canonical-catalog.xml</resource>
							</dependencyResource>
						</catalog>
					</catalogs>
					<catalogResolver>org.jvnet.jaxb2.maven2.resolver.tools.ClasspathCatalogResolver</catalogResolver>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
````

My existing catalog has also stayed the same

````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog
    PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
	<public publicId="http://myco.com/rms/schemas/cartonrounding/tolerance/v1_0" uri="classpath:CartonRoundingTolerance_1_0.xsd" />
	<public publicId="http://myco.com/rms/schemas/distribution/transfer/v1_0" uri="classpath:Transfer_1_0.xsd" />
	<public publicId="http://myco.com/rms/schemas/hts/htscode/v1_0" uri="classpath:HTSCode_1_0.xsd" />
	<public publicId="http://myco.com/rms/schemas/inventory/stock/v1_0" uri="classpath:Stock_1_0.xsd" />
````

Anything obviously wrong ?

**Comment by highsource** [comment]
I think there's a conflict with the classpath catalog resolver. Please remove the `<catalogResolver .../>` configuration element an change `classpath:...` into `maven:...` style URIs.

It also helps to see the full `mvn -X -e` log.

I think you're hitting one of the changes introduced around `0.10.0`. There was a number of fixes on catalog resolution back then. It's a bit hard to guess what's wrong without the reproducing project, but I'd blame the catalog resolver.

Resolving `maven:...` URIs works quite stable. Here's a catalog from a large project which relies heavily on that:

https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources/ogc/catalog.cat

**Comment by highsource** [comment]
I hope the question is answered so I'll close the issue.

**Comment by gbonk** [comment]
Not really. I just stopped messing with it and reverted.   I'll try again and if it's still an issue I'll get back.
