### ISSUE TITLE
Unable to resolve relative import located within same dependencyResource artifact

### ISSUE THREAD

**Issue by jpraet** [highsource/maven-jaxb2-plugin#83]
I'm trying to configure the plugin with a dependencyResource jar that contains 2 XSD. One XSD is importing the other with an <xs:import /> specifying the relative path.

But the plugin cannot resolve the imported XSD:

> [WARNING] Error while parsing schema(s).Location [ maven:XYZ:XYZ:xsd::!XYZ.xsd{15,114}].
org.xml.sax.SAXParseException; systemId: maven:XYZ:XYZ:xsd::!XYZ.xsd; lineNumber: 15; columnNumber: 114; schema_reference.4: Failed to read schema document '../../types/common/CommonV3.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:392)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4158)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(XSDHandler.java:4153)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2486)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2183)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.resolveSchema(XSDHandler.java:2074)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.constructTrees(XSDHandler.java:1004)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:616)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:613)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:572)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:538)
        at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
        at com.sun.tools.xjc.reader.xmlschema.parser.SchemaConstraintChecker.check(SchemaConstraintChecker.java:111)
        at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:360)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
        at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
        at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
        at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
        ...
Caused by: java.net.MalformedURLException: unknown protocol: maven
        at java.net.URL.<init>(URL.java:600)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:620)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:582)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:685)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2171)
        ... 37 more

**Comment by highsource** [comment]
I'd need a reproducing test case for this please PR a test case here:

https://github.com/highsource/maven-jaxb2-plugin-support

under issues/gh83.

Thanks

This should actually work, I have quite a lot relative paths in projects
like ogc-schemas.

**Comment by jpraet** [comment]
test case: https://github.com/highsource/maven-jaxb2-plugin-support/pull/1

**Comment by highsource** [comment]
Here's a workaroudÖ

https://github.com/highsource/maven-jaxb2-plugin-support/commit/e5d7434b66d6edb09c4eec2f158c67d35ea6ae6e

**Comment by DiabolusExMachina** [comment]
Hi, 

will this anytime soon work out of the box? We have the same problem. We have a WSDL multiple nested relative imports of XSD Files in a complex folder structure (The files are generated). 

I'm not sure if your workaround will work in such a scenario.

**Comment by DranonJoD** [comment]
Still no fix?

**Comment by highsource** [comment]
I'm not sure, I thought I have fixed it. I'll check.

**Comment by dlmiles** [comment]
> I'm not sure if your workaround will work in such a scenario.

Surely you can have 2 projects (like 2 pom.xml) and one project is responsible for obtaining and generating the WSDL file and emitting the output inside a JAR.

The other project has the above as a dependency and is responsible for taking that WSDL from inside the JAR and generate classes that also outputs a JAR.  maven-jaxb2-plugin has the amazing feature to reference the resource inside a dependant JAR to locate WSDLs.

**Comment by delanym** [comment]
Today my build failed temporarily. Even though a local schemaLocation is set, the plugin went online, and failed because presumably the remote server was down.

**Comment by delanym** [comment]
I had a different issue, caused by the DOCTYPE declaration. Only solution was to remove it
https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd
Same issue in the cxf-xjc-plugin.
